before_commands:
    - "composer install --prefer-source"

tools:
    external_code_coverage: true
    php_pdepend: true
    php_analyzer: true
    php_mess_detector: true
    sensiolabs_security_checker: true
